version: "3.8"

services:
    mongo:
        image: mongo
        restart: always
        volumes:
            - ./data:/data/db
        ports:
        - 27017:27017
    mongoex:
        container_name: mongoex
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        links:
            - mongo